// GENERATED by behavior-contracts (go-typed-native) — the BC-OWNED shared wire types. A covered module
// generated with --shared-types-import imports this; a separate leaf-transport package takes a WireRow
// payload + returns its WireValue. Self-contained + runtime-free.
package wire

import "strconv"

// Probe kinds — the outcome of classifying one wire attribute against a declared field type.
const (
	probeGot    uint8 = 0 // present; the wire variant matches the declared type
	probeWrong  uint8 = 1 // present but a different wire variant (carries ActualWireType + Raw)
	probeAbsent uint8 = 2 // no attribute for this field
	probeNull   uint8 = 3 // present as the producer's null variant (opt → None; required → mismatch)
)

// Probe RESULT structs — concrete data the WireValue classifiers hand back; the de-box reads .Kind /
// .Got / .ActualWireType / .Raw (exported fields).

// StringProbe / IntProbe / FloatProbe / BoolProbe — a scalar probe result. Got holds the matched value
// already in its declared type — the wire carries int and float natively, so nothing is parsed. ActualWireType is the
// producer's own wire tag (a free string, e.g. a DynamoDB "S"/"N"/"BOOL"); Raw is the offending value
// stringified. Concrete structs — no boxed Value crosses the seam.
type StringProbe struct {
	Kind           uint8
	Got            string
	ActualWireType string
	Raw            string
}

type IntProbe struct {
	Kind           uint8
	Got            int64
	ActualWireType string
	Raw            string
}

type FloatProbe struct {
	Kind           uint8
	Got            float64
	ActualWireType string
	Raw            string
}

type BoolProbe struct {
	Kind           uint8
	Got            bool
	ActualWireType string
	Raw            string
}

// RowProbe / ListProbe — a composite probe result: a nested wire map (a DynamoDB "M") or wire array (an
// "L"). Got is the consumer's CONCRETE WireRow / WireList (a value type — no boxed Value, no
// interface); the inline de-box probes it directly.
type RowProbe struct {
	Kind           uint8
	Got            WireRow
	ActualWireType string
	Raw            string
}

type ListProbe struct {
	Kind           uint8
	Got            WireList
	ActualWireType string
	Raw            string
}

// WireValue — the BC-OWNED generic result the consumer's single op-agnostic transport builds + returns
// (WireStr/WireInt/WireFloat/WireBool/WireNull/WireRowOf/WireListOf) and implements NOTHING over.
// A self-contained tagged union (no untyped box, no bc-runtime Value); numbers are NATIVE (int64 / float64),
// so the de-box parses nothing. Composite = nested Entries (row) / Items (list).
type WireValue struct {
	kind    uint8
	str     string
	i64v    int64
	f64v    float64
	bl      bool
	Entries []WireField
	Items   []WireValue
}

type WireField struct {
	Key string
	Val WireValue
}

// WireRow / WireList — a wire map / array handle over a SHARED slice backing (value type; probes return the
// bc probe RESULT structs). The generated de-box probes them by declared field / element.
type WireRow struct {
	entries []WireField
}

type WireList struct {
	items []WireValue
}

const (
	wireNull uint8 = 0
	wireStr  uint8 = 1
	wireInt  uint8 = 2
	wireFloat uint8 = 6
	wireBool uint8 = 3
	wireRow  uint8 = 4
	wireList uint8 = 5
)

// constructors the consumer's transport uses to build the result (numbers carried natively).
func WireStr(s string) WireValue          { return WireValue{kind: wireStr, str: s} }
func WireInt(n int64) WireValue           { return WireValue{kind: wireInt, i64v: n} }
func WireFloat(f float64) WireValue       { return WireValue{kind: wireFloat, f64v: f} }
func WireBool(b bool) WireValue           { return WireValue{kind: wireBool, bl: b} }
func WireNull() WireValue                 { return WireValue{kind: wireNull} }
func WireRowOf(fields []WireField) WireValue { return WireValue{kind: wireRow, Entries: fields} }
func WireListOf(items []WireValue) WireValue { return WireValue{kind: wireList, Items: items} }

// WireRowOfFields — build a WireRow (the op-agnostic transport PAYLOAD type, #183) from named fields. The
// covered runner assembles the payload; the spec-named leaf transport reads its fields BY NAME
// (payload.ProbeString("PK") …), so divergent port SETS across roles are just different field lists in the
// SAME WireRow — ONE transport signature <Leaf>(payload WireRow) (WireValue, error) serves every role.
func WireRowOfFields(fields []WireField) WireRow { return WireRow{entries: fields} }

// IsNull — is this the wire null value? A batched/fanout transport returns a WireList of aligned results; a
// DANGLING fanout id is a WireNull element the covered runner detects here (drop:dangling) before de-box.
func (w WireValue) IsNull() bool { return w.kind == wireNull }

func (w *WireValue) wireTag() string {
	switch w.kind {
	case wireStr:
		return "S"
	case wireInt, wireFloat:
		return "N"
	case wireBool:
		return "BOOL"
	case wireRow:
		return "M"
	case wireList:
		return "L"
	default:
		return "NULL"
	}
}
func (w *WireValue) wireRaw() string {
	switch w.kind {
	case wireStr:
		return w.str
	case wireInt:
		return strconv.FormatInt(w.i64v, 10)
	case wireFloat:
		return strconv.FormatFloat(w.f64v, 'g', -1, 64)
	case wireBool:
		if w.bl {
			return "true"
		}
		return "false"
	case wireNull:
		return "null"
	default:
		return "[composite]"
	}
}

// the top result is always present; field/elem probes share the same classifiers over *WireValue (nil = absent).
// Value receivers: a hand-written transport reads its payload off values the compiler will not let it
// address (a function result, a map element), so the probe surface stays callable on a value.
func (w WireValue) AsString() StringProbe { return ProbeStringOf(&w) }
func (w WireValue) AsInt() IntProbe       { return ProbeIntOf(&w) }
func (w WireValue) AsFloat() FloatProbe   { return ProbeFloatOf(&w) }
func (w WireValue) AsBool() BoolProbe     { return ProbeBoolOf(&w) }
func (w WireValue) AsRow() RowProbe       { return ProbeRowOf(&w) }
func (w WireValue) AsList() ListProbe     { return ProbeListOf(&w) }

func (r WireRow) get(field string) *WireValue {
	for i := range r.entries {
		if r.entries[i].Key == field {
			return &r.entries[i].Val
		}
	}
	return nil
}
// Entries — the row's fields as they are. A dynamic-keyed map de-box walks these directly instead of
// materialising a []string of keys per row and then looking each one up again.
func (r WireRow) Entries() []WireField { return r.entries }

func (r WireRow) ProbeString(field string) StringProbe { return ProbeStringOf(r.get(field)) }
func (r WireRow) ProbeInt(field string) IntProbe       { return ProbeIntOf(r.get(field)) }
func (r WireRow) ProbeFloat(field string) FloatProbe   { return ProbeFloatOf(r.get(field)) }
func (r WireRow) ProbeBool(field string) BoolProbe     { return ProbeBoolOf(r.get(field)) }
func (r WireRow) ProbeRow(field string) RowProbe       { return ProbeRowOf(r.get(field)) }
func (r WireRow) ProbeList(field string) ListProbe     { return ProbeListOf(r.get(field)) }

func (l WireList) Len() int                     { return len(l.items) }
func (l WireList) ElemString(i int) StringProbe { return ProbeStringOf(&l.items[i]) }
func (l WireList) ElemInt(i int) IntProbe       { return ProbeIntOf(&l.items[i]) }
func (l WireList) ElemFloat(i int) FloatProbe   { return ProbeFloatOf(&l.items[i]) }
func (l WireList) ElemBool(i int) BoolProbe     { return ProbeBoolOf(&l.items[i]) }
func (l WireList) ElemRow(i int) RowProbe       { return ProbeRowOf(&l.items[i]) }
func (l WireList) ElemList(i int) ListProbe     { return ProbeListOf(&l.items[i]) }

// the ONE classifier per kind, over *WireValue (nil = absent attribute/element). The BC-owned variant IS
// the wire tag — no consumer classification.
func ProbeStringOf(w *WireValue) StringProbe {
	if w == nil {
		return StringProbe{Kind: probeAbsent}
	}
	switch w.kind {
	case wireStr:
		return StringProbe{Kind: probeGot, Got: w.str, ActualWireType: "S", Raw: w.str}
	case wireNull:
		return StringProbe{Kind: probeNull, ActualWireType: "NULL", Raw: "null"}
	default:
		return StringProbe{Kind: probeWrong, ActualWireType: w.wireTag(), Raw: w.wireRaw()}
	}
}
func ProbeIntOf(w *WireValue) IntProbe {
	if w == nil {
		return IntProbe{Kind: probeAbsent}
	}
	switch w.kind {
	case wireInt:
		return IntProbe{Kind: probeGot, Got: w.i64v, ActualWireType: "N"}
	case wireFloat:
		// an int position accepts an INTEGRAL float and narrows it EXACTLY — the mirror of the widening
		// below. A wire numeric type that spells the same attribute 1 or 1.0 leaves the producer no way to
		// pick the variant. Non-integral, or beyond int64, stays LOUD (an exact conversion with a
		// fail-closed boundary, not a fallback).
		if f := w.f64v; f >= -9223372036854775808.0 && f < 9223372036854775808.0 && float64(int64(f)) == f {
			return IntProbe{Kind: probeGot, Got: int64(f), ActualWireType: "N"}
		}
		return IntProbe{Kind: probeWrong, ActualWireType: w.wireTag(), Raw: w.wireRaw()}
	case wireNull:
		return IntProbe{Kind: probeNull, ActualWireType: "NULL", Raw: "null"}
	default:
		return IntProbe{Kind: probeWrong, ActualWireType: w.wireTag(), Raw: w.wireRaw()}
	}
}

// a float position accepts an int and widens it — the same widening the interpreter's outType check does.
func ProbeFloatOf(w *WireValue) FloatProbe {
	if w == nil {
		return FloatProbe{Kind: probeAbsent}
	}
	switch w.kind {
	case wireFloat:
		return FloatProbe{Kind: probeGot, Got: w.f64v, ActualWireType: "N"}
	case wireInt:
		return FloatProbe{Kind: probeGot, Got: float64(w.i64v), ActualWireType: "N"}
	case wireNull:
		return FloatProbe{Kind: probeNull, ActualWireType: "NULL", Raw: "null"}
	default:
		return FloatProbe{Kind: probeWrong, ActualWireType: w.wireTag(), Raw: w.wireRaw()}
	}
}
func ProbeBoolOf(w *WireValue) BoolProbe {
	if w == nil {
		return BoolProbe{Kind: probeAbsent}
	}
	switch w.kind {
	case wireBool:
		return BoolProbe{Kind: probeGot, Got: w.bl, ActualWireType: "BOOL", Raw: w.wireRaw()}
	case wireNull:
		return BoolProbe{Kind: probeNull, ActualWireType: "NULL", Raw: "null"}
	default:
		return BoolProbe{Kind: probeWrong, ActualWireType: w.wireTag(), Raw: w.wireRaw()}
	}
}
func ProbeRowOf(w *WireValue) RowProbe {
	if w == nil {
		return RowProbe{Kind: probeAbsent}
	}
	switch w.kind {
	case wireRow:
		return RowProbe{Kind: probeGot, Got: WireRow{entries: w.Entries}, ActualWireType: "M"}
	case wireNull:
		return RowProbe{Kind: probeNull, ActualWireType: "NULL", Raw: "null"}
	default:
		return RowProbe{Kind: probeWrong, ActualWireType: w.wireTag(), Raw: w.wireRaw()}
	}
}
func ProbeListOf(w *WireValue) ListProbe {
	if w == nil {
		return ListProbe{Kind: probeAbsent}
	}
	switch w.kind {
	case wireList:
		return ListProbe{Kind: probeGot, Got: WireList{items: w.Items}, ActualWireType: "L"}
	case wireNull:
		return ListProbe{Kind: probeNull, ActualWireType: "NULL", Raw: "null"}
	default:
		return ListProbe{Kind: probeWrong, ActualWireType: w.wireTag(), Raw: w.wireRaw()}
	}
}
