#![allow(dead_code, unused_imports, non_snake_case)]
// GENERATED by behavior-contracts (rust-typed-native) — the BC-OWNED shared wire types (#165). A covered
// module generated with --shared-types-import imports these (`use <path>::*;`); a separate leaf-transport
// crate takes a `WireRow` payload + builds + returns the SAME `WireValue` (and, on failure, the SAME
// `BehaviorError`). The concrete failure type lives here too so the transport crate returns
// `Result<WireValue, BehaviorError>` WITHOUT importing the covered crate (unlike go's `error` interface,
// rust's runner reads the concrete `.detail`/`.message`, so the type must be shared). Self-contained.

// Local concrete failure type (runtime-free) — the covered runner + the transport crate share it. Only the
// TYPE lives here; the de-box/op-failure CONSTRUCTORS stay in the covered module (they are called there).
use std::borrow::Cow;

// ErrorKind — what went wrong (the closed set of scp-error.md). A concrete enum: the covered plane
// carries no strings-as-tags and no dynamic kind lookup.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ErrorKind {
    TypeMismatch,
    MissingField,
    Overflow,
}

impl ErrorKind {
    pub fn as_str(self) -> &'static str {
        match self {
            ErrorKind::TypeMismatch => "typeMismatch",
            ErrorKind::MissingField => "missingField",
            ErrorKind::Overflow => "overflow",
        }
    }
}

// ErrorDetail — the structured, recoverable payload a failure carries (scp-error.md "The Error
// Value"). The LEAF produces it at the wire boundary (it is the only party holding both the declared
// type and the raw wire datum); the runner transports it verbatim. Concrete fields — no boxed Value,
// no serialized blob in a string: `expected_type` is Portable Type Notation, a rendering of a
// STATICALLY DECLARED type, so nothing walks a type at runtime.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct ErrorDetail {
    pub kind: Option<ErrorKind>,
    pub model: Option<String>,
    pub field: Option<String>,
    pub expected_type: Option<String>,
    pub actual_wire_type: Option<String>,
    pub raw_value: Option<String>,
    pub context: std::collections::BTreeMap<String, String>,
}

// BehaviorError — the LOCAL concrete failure type for the covered read plane (runtime-free): a
// covered runner returns `Result<T, BehaviorError>` over THIS local type instead of a bc-runtime
// failure, so the fully-covered module imports ZERO bc runtime. Codes match run_behavior verbatim
// (byte-equal). `detail` carries the leaf's structured Error Value across the seam so a caller can
// log / skip / repair / migrate rather than parse a message. The covered module stays runtime-free:
// nothing in it converts this local error into a bc-runtime failure.
#[derive(Debug, Clone)]
pub struct BehaviorError {
    pub code: String,
    pub message: String,
    pub detail: Option<Box<ErrorDetail>>,
}

impl BehaviorError {
    pub fn new(code: impl Into<String>, message: impl Into<String>) -> Self {
        BehaviorError {
            code: code.into(),
            message: message.into(),
            detail: None,
        }
    }
    /// The same failure carrying the leaf's structured Error Value.
    pub fn with_detail(
        code: impl Into<String>,
        message: impl Into<String>,
        detail: ErrorDetail,
    ) -> Self {
        BehaviorError {
            code: code.into(),
            message: message.into(),
            detail: Some(Box::new(detail)),
        }
    }
    /// The stable failure code (byte-equal to run_behavior) WITHOUT a bc-runtime type.
    pub fn code(&self) -> &str {
        &self.code
    }
    /// The structured payload, if this failure is about a datum.
    pub fn detail(&self) -> Option<&ErrorDetail> {
        self.detail.as_deref()
    }
}

impl std::fmt::Display for BehaviorError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}: {}", self.code, self.message)
    }
}
impl std::error::Error for BehaviorError {}

// Probe<T> — the outcome of classifying one wire attribute against a declared type. Got carries
// the matched value MOVED OUT of the wire (a number arrives already native, so there is nothing to parse
// and no range check to fail); actual_wire_type is the producer's own wire tag
// (S/N/BOOL/M/L/NULL), a `&'static str` so classifying costs NO allocation; raw_value is the offending
// value, borrowed when it is a fixed word. Concrete enums — no boxed runtime value.
//
// NO COPY TO READ. Classification CONSUMES the wire: the transport's result is an owned local that is dead
// the moment it is de-boxed, so every string / row / list is MOVED into the typed value. Copying a result
// set here would be a heap copy of every cell once per node boundary, it scales with node count, and it is
// what made a generated native read lose to an interpreter. The codegen purity gate enforces this by naming
// the copying spellings and failing the build on them: a wire classifier that BORROWS (which forces a
// per-cell copy to de-box), a de-box that clones a list out of the wire, and a row cloned out of its cell
// before a field is taken from the copy. Owning ONE leaf value that a borrow cannot outlive is not a copy
// of the result set and is not forbidden.
pub enum Probe<T> {
    Got(T),
    Wrong {
        actual_wire_type: &'static str,
        raw_value: Cow<'static, str>,
    },
    Null {
        actual_wire_type: &'static str,
        raw_value: Cow<'static, str>,
    },
    Absent,
}

// WireValue — the BC-OWNED, BC-GENERATED, self-contained (runtime-free) generic result the consumer's
// single op-agnostic transport returns. The consumer BUILDS it as it reads the producer (the raw I/O act)
// — WireValue::Str/Int/Float/Bool/Null/Row/List, or the int()/float() constructors — and implements NOTHING
// over it. Numbers are NATIVE (i64 / f64): the producer's own integer reaches the de-box unparsed. A
// composite is a nested WireRow / WireList. NO trait, NO consumer classification protocol.
#[derive(Clone)]
pub enum WireValue {
    Str(Cow<'static, str>),
    Int(i64),
    Float(f64),
    Bool(bool),
    Null,
    Row(WireRow),
    List(WireList),
}

// WireRow / WireList — a wire map (a DynamoDB "M") / wire array (an "L"). Native Vec-backed; the generated
// de-box drains them by declared field / element and owns strictness (required/optional, present/absent,
// error assembly).
//
// A key is `Cow<'static, str>`: the field names BC generates are compile-time constants and ride as
// `Cow::Borrowed` (zero allocation, however many times a payload is built), while a producer-supplied key
// read at run time rides as `Cow::Owned`. The same holds for Str — a generated SQL literal costs
// nothing per call, a value read off the wire owns its text.
#[derive(Clone)]
pub struct WireRow {
    pub entries: Vec<(Cow<'static, str>, WireValue)>,
}

#[derive(Clone)]
pub struct WireList {
    pub items: Vec<WireValue>,
}

impl WireValue {
    // constructors the consumer's transport uses to build numeric results (i64 / f64, carried natively).
    pub fn int(n: i64) -> Self {
        WireValue::Int(n)
    }
    pub fn float(n: f64) -> Self {
        WireValue::Float(n)
    }
    fn tag(&self) -> &'static str {
        match self {
            WireValue::Str(_) => "S",
            WireValue::Int(_) | WireValue::Float(_) => "N",
            WireValue::Bool(_) => "BOOL",
            WireValue::Null => "NULL",
            WireValue::Row(_) => "M",
            WireValue::List(_) => "L",
        }
    }
    // the offending value as text, for a failure detail. CONSUMES the value (the cold path owns it by
    // then), so reporting a wrong string moves it out instead of copying it.
    fn into_raw(self) -> Cow<'static, str> {
        match self {
            WireValue::Str(s) => s,
            WireValue::Int(n) => Cow::Owned(n.to_string()),
            WireValue::Float(f) => Cow::Owned(f.to_string()),
            WireValue::Bool(b) => Cow::Owned(b.to_string()),
            WireValue::Null => Cow::Borrowed("null"),
            WireValue::Row(_) | WireValue::List(_) => Cow::Borrowed("[composite]"),
        }
    }
}

impl WireRow {
    // Move the value at `field` OUT of the row (or None when the producer did not send it). The de-box
    // reads each declared field exactly once, so taking is always right — and it is what keeps a cell
    // from being copied: the String travels from the wire into the typed struct without a heap copy.
    // Undeclared extras are simply left behind with the row.
    pub fn take(&mut self, field: &str) -> Option<WireValue> {
        self.entries
            .iter()
            .position(|(k, _)| k == field)
            .map(|i| self.entries.swap_remove(i).1)
    }
}

// the ONE classifier per kind, over an OWNED Option<WireValue> (None = absent attribute/element). The
// BC-owned WireValue variant IS the wire tag — no consumer classification. Each takes the value BY VALUE
// and hands the match MOVED OUT: de-boxing a result never copies a cell, a row, or a list.
pub fn probe_string_at(v: Option<WireValue>) -> Probe<Cow<'static, str>> {
    match v {
        None => Probe::Absent,
        Some(WireValue::Str(s)) => Probe::Got(s),
        Some(WireValue::Null) => Probe::Null {
            actual_wire_type: "NULL",
            raw_value: Cow::Borrowed("null"),
        },
        Some(o) => Probe::Wrong {
            actual_wire_type: o.tag(),
            raw_value: o.into_raw(),
        },
    }
}
pub fn probe_int_at(v: Option<WireValue>) -> Probe<i64> {
    match v {
        None => Probe::Absent,
        Some(WireValue::Int(n)) => Probe::Got(n),
        // an int position accepts an INTEGRAL float and narrows it EXACTLY — the mirror of the widening
        // below. A wire numeric type that spells the same attribute 1 or 1.0 leaves the producer no way to
        // pick the variant. Non-integral, or beyond i64, stays LOUD (an exact conversion with a
        // fail-closed boundary, not a fallback).
        Some(WireValue::Float(f))
            if (-9223372036854775808.0..9223372036854775808.0).contains(&f) && f == f.trunc() =>
        {
            Probe::Got(f as i64)
        }
        Some(WireValue::Null) => Probe::Null {
            actual_wire_type: "NULL",
            raw_value: Cow::Borrowed("null"),
        },
        Some(o) => Probe::Wrong {
            actual_wire_type: o.tag(),
            raw_value: o.into_raw(),
        },
    }
}
// a float position accepts an int and widens it — the same widening the interpreter's outType check does,
// so the generated read and run_behavior agree on an integral value in a float field.
pub fn probe_float_at(v: Option<WireValue>) -> Probe<f64> {
    match v {
        None => Probe::Absent,
        Some(WireValue::Float(f)) => Probe::Got(f),
        Some(WireValue::Int(n)) => Probe::Got(n as f64),
        Some(WireValue::Null) => Probe::Null {
            actual_wire_type: "NULL",
            raw_value: Cow::Borrowed("null"),
        },
        Some(o) => Probe::Wrong {
            actual_wire_type: o.tag(),
            raw_value: o.into_raw(),
        },
    }
}
pub fn probe_bool_at(v: Option<WireValue>) -> Probe<bool> {
    match v {
        None => Probe::Absent,
        Some(WireValue::Bool(b)) => Probe::Got(b),
        Some(WireValue::Null) => Probe::Null {
            actual_wire_type: "NULL",
            raw_value: Cow::Borrowed("null"),
        },
        Some(o) => Probe::Wrong {
            actual_wire_type: o.tag(),
            raw_value: o.into_raw(),
        },
    }
}
pub fn probe_row_at(v: Option<WireValue>) -> Probe<WireRow> {
    match v {
        None => Probe::Absent,
        Some(WireValue::Row(r)) => Probe::Got(r),
        Some(WireValue::Null) => Probe::Null {
            actual_wire_type: "NULL",
            raw_value: Cow::Borrowed("null"),
        },
        Some(o) => Probe::Wrong {
            actual_wire_type: o.tag(),
            raw_value: o.into_raw(),
        },
    }
}
pub fn probe_list_at(v: Option<WireValue>) -> Probe<WireList> {
    match v {
        None => Probe::Absent,
        Some(WireValue::List(l)) => Probe::Got(l),
        Some(WireValue::Null) => Probe::Null {
            actual_wire_type: "NULL",
            raw_value: Cow::Borrowed("null"),
        },
        Some(o) => Probe::Wrong {
            actual_wire_type: o.tag(),
            raw_value: o.into_raw(),
        },
    }
}
