# GENERATED by behavior-contracts common generator (bc#13) — DO NOT EDIT.
# Input: portable component-graph IR only (scp-ir-architecture.md §5/§7.4).
# This module is the codegen endpoint (§7.3 endpoint 3): the IR is embedded as a
# native dict literal and handed to the EXISTING runtime core (run_behavior) —
# no execution logic is generated. Handlers are ALWAYS injected at the boundary
# (IR + {effects,config,hooks}); they are never generated.
# irFingerprint: fnv1a64:82fabfaf5e5b3621
from behavior_contracts import SPEC_VERSIONS, ProvenanceError, load_compiled_ir, run_behavior

# Spec versions baked at generation time (fail-closed constant comparison at load).
EXPECTED_SPEC_VERSIONS = {"behavior": 5, "expression": 2, "plan": 1}

# FNV-1a 64 fingerprint of the source portable IR (canonical_json discipline, #208).
IR_FINGERPRINT = "fnv1a64:82fabfaf5e5b3621"

# Component names exposed by bind(), in IR declaration order.
COMPONENT_NAMES = ("posts", "postsTop", "page", "postsByIds", "feed", "usersWithPosts", "postsWithAuthor", "usersWithCappedPosts", "usersWithUncappedPosts", "usersWithTopPosts", "createPost", "renamePost", "removePost", "createPostReturning", "renamePostReturning", "removePostReturning", "typedRows", "createTags", "removeTags")

# The portable component-graph IR *document*, embedded as a native dict literal (no JSON parse at
# runtime). It carries no provenance token — the load-time load_compiled_ir() below verifies the baked
# fingerprint and mints the in-process handle (serialized IR crosses the boundary via the
# fingerprint-gated loader, ONCE at load — never per call).
IR_DOC = {
  "irVersion": 3,
  "exprVersion": 2,
  "components": [
    {
      "body": [
        {
          "component": "executeSQL",
          "id": "n0",
          "outType": {
            "arr": {
              "name": "PostsRow",
              "obj": {
                "author_id": {
                  "opt": "float"
                },
                "created_at": {
                  "opt": "string"
                },
                "id": {
                  "opt": "float"
                },
                "status": {
                  "opt": "string"
                },
                "title": {
                  "opt": "string"
                }
              }
            }
          },
          "portSchemas": {
            "bigint": {
              "required": True,
              "type": "bool"
            },
            "params": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "returning": {
              "required": True,
              "type": "bool"
            },
            "sql": {
              "required": True,
              "type": "string"
            },
            "write": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "bigint": False,
            "params": {
              "arr": [
                {
                  "ref": [
                    "authorId"
                  ]
                }
              ]
            },
            "returning": False,
            "sql": "SELECT id, author_id, title, status, created_at FROM conf_posts WHERE author_id = ? ORDER BY id ASC",
            "write": False
          }
        }
      ],
      "inputPorts": {
        "authorId": {
          "required": True,
          "type": "int"
        }
      },
      "name": "posts",
      "output": {
        "ref": [
          "n0"
        ]
      },
      "plan": {
        "concurrency": 16,
        "groups": [
          [
            0
          ]
        ]
      },
      "outputType": {
        "arr": {
          "obj": {
            "author_id": {
              "opt": "float"
            },
            "created_at": {
              "opt": "string"
            },
            "id": {
              "opt": "float"
            },
            "status": {
              "opt": "string"
            },
            "title": {
              "opt": "string"
            }
          },
          "name": "PostsRow"
        }
      }
    },
    {
      "body": [
        {
          "component": "executeSQL",
          "id": "n0",
          "outType": {
            "arr": {
              "name": "PostsTopRow",
              "obj": {
                "author_id": {
                  "opt": "float"
                },
                "created_at": {
                  "opt": "string"
                },
                "id": {
                  "opt": "float"
                },
                "status": {
                  "opt": "string"
                },
                "title": {
                  "opt": "string"
                }
              }
            }
          },
          "portSchemas": {
            "bigint": {
              "required": True,
              "type": "bool"
            },
            "params": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "returning": {
              "required": True,
              "type": "bool"
            },
            "sql": {
              "required": True,
              "type": "string"
            },
            "write": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "bigint": False,
            "params": {
              "arr": []
            },
            "returning": False,
            "sql": "SELECT id, author_id, title, status, created_at FROM conf_posts ORDER BY id ASC LIMIT 2",
            "write": False
          }
        }
      ],
      "inputPorts": {},
      "name": "postsTop",
      "output": {
        "ref": [
          "n0"
        ]
      },
      "plan": {
        "concurrency": 16,
        "groups": [
          [
            0
          ]
        ]
      },
      "outputType": {
        "arr": {
          "obj": {
            "author_id": {
              "opt": "float"
            },
            "created_at": {
              "opt": "string"
            },
            "id": {
              "opt": "float"
            },
            "status": {
              "opt": "string"
            },
            "title": {
              "opt": "string"
            }
          },
          "name": "PostsTopRow"
        }
      }
    },
    {
      "body": [
        {
          "component": "executeSQL",
          "id": "n0",
          "outType": {
            "arr": {
              "name": "PageRow",
              "obj": {
                "id": {
                  "opt": "float"
                },
                "title": {
                  "opt": "string"
                }
              }
            }
          },
          "portSchemas": {
            "bigint": {
              "required": True,
              "type": "bool"
            },
            "params": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "returning": {
              "required": True,
              "type": "bool"
            },
            "sql": {
              "required": True,
              "type": "string"
            },
            "write": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "bigint": False,
            "params": {
              "arr": [
                {
                  "ref": [
                    "limit"
                  ]
                },
                {
                  "ref": [
                    "offset"
                  ]
                }
              ]
            },
            "returning": False,
            "sql": "SELECT id, title FROM conf_posts ORDER BY id ASC LIMIT ? OFFSET ?",
            "write": False
          }
        }
      ],
      "inputPorts": {
        "limit": {
          "required": True,
          "type": "int"
        },
        "offset": {
          "required": True,
          "type": "int"
        }
      },
      "name": "page",
      "output": {
        "ref": [
          "n0"
        ]
      },
      "plan": {
        "concurrency": 16,
        "groups": [
          [
            0
          ]
        ]
      },
      "outputType": {
        "arr": {
          "obj": {
            "id": {
              "opt": "float"
            },
            "title": {
              "opt": "string"
            }
          },
          "name": "PageRow"
        }
      }
    },
    {
      "body": [
        {
          "component": "executeSQL",
          "id": "n0",
          "outType": {
            "arr": {
              "name": "PostsByIdsRow",
              "obj": {
                "id": {
                  "opt": "float"
                },
                "title": {
                  "opt": "string"
                }
              }
            }
          },
          "portSchemas": {
            "bigint": {
              "required": True,
              "type": "bool"
            },
            "params": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "returning": {
              "required": True,
              "type": "bool"
            },
            "sql": {
              "required": True,
              "type": "string"
            },
            "write": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "bigint": False,
            "params": {
              "arr": [
                {
                  "ref": [
                    "ids"
                  ]
                }
              ]
            },
            "returning": False,
            "sql": "SELECT id, title FROM conf_posts WHERE id = ANY(?) ORDER BY id ASC",
            "write": False
          }
        }
      ],
      "inputPorts": {
        "ids": {
          "elemType": "int",
          "required": True,
          "type": "array"
        }
      },
      "name": "postsByIds",
      "output": {
        "ref": [
          "n0"
        ]
      },
      "plan": {
        "concurrency": 16,
        "groups": [
          [
            0
          ]
        ]
      },
      "outputType": {
        "arr": {
          "obj": {
            "id": {
              "opt": "float"
            },
            "title": {
              "opt": "string"
            }
          },
          "name": "PostsByIdsRow"
        }
      }
    },
    {
      "body": [
        {
          "component": "executeSQL",
          "id": "n0",
          "outType": {
            "arr": {
              "name": "FeedRow",
              "obj": {
                "author_id": {
                  "opt": "float"
                },
                "id": {
                  "opt": "float"
                },
                "status": {
                  "opt": "string"
                },
                "title": {
                  "opt": "string"
                }
              }
            }
          },
          "portSchemas": {
            "bigint": {
              "required": True,
              "type": "bool"
            },
            "params": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "returning": {
              "required": True,
              "type": "bool"
            },
            "sql": {
              "required": True,
              "type": "string"
            },
            "whereDynamic": {
              "required": False,
              "type": "value"
            },
            "write": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "bigint": False,
            "params": {
              "arr": []
            },
            "returning": False,
            "sql": "SELECT id, author_id, title, status FROM conf_posts ORDER BY id ASC",
            "whereDynamic": {
              "obj": {
                "frags": {
                  "arr": [
                    {
                      "obj": {
                        "params": {
                          "arr": [
                            {
                              "ref": [
                                "authorId"
                              ]
                            }
                          ]
                        },
                        "sql": "author_id = ?"
                      }
                    },
                    {
                      "cond": [
                        {
                          "ne": [
                            {
                              "ref": [
                                "status"
                              ]
                            },
                            None
                          ]
                        },
                        {
                          "obj": {
                            "params": {
                              "arr": [
                                {
                                  "ref": [
                                    "status"
                                  ]
                                }
                              ]
                            },
                            "sql": "status = ?"
                          }
                        },
                        None
                      ]
                    },
                    {
                      "cond": [
                        {
                          "ne": [
                            {
                              "ref": [
                                "since"
                              ]
                            },
                            None
                          ]
                        },
                        {
                          "obj": {
                            "params": {
                              "arr": [
                                {
                                  "ref": [
                                    "since"
                                  ]
                                }
                              ]
                            },
                            "sql": "created_at >= ?"
                          }
                        },
                        None
                      ]
                    }
                  ]
                }
              }
            },
            "write": False
          }
        }
      ],
      "inputPorts": {
        "authorId": {
          "required": True,
          "type": "int"
        },
        "since": {
          "required": False,
          "type": "string"
        },
        "status": {
          "required": False,
          "type": "string"
        }
      },
      "name": "feed",
      "output": {
        "ref": [
          "n0"
        ]
      },
      "plan": {
        "concurrency": 16,
        "groups": [
          [
            0
          ]
        ]
      },
      "outputType": {
        "arr": {
          "obj": {
            "author_id": {
              "opt": "float"
            },
            "id": {
              "opt": "float"
            },
            "status": {
              "opt": "string"
            },
            "title": {
              "opt": "string"
            }
          },
          "name": "FeedRow"
        }
      }
    },
    {
      "body": [
        {
          "component": "executeSQL",
          "id": "n0",
          "outType": {
            "arr": "value"
          },
          "portSchemas": {
            "bigint": {
              "required": True,
              "type": "bool"
            },
            "params": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "returning": {
              "required": True,
              "type": "bool"
            },
            "sql": {
              "required": True,
              "type": "string"
            },
            "write": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "bigint": False,
            "params": {
              "arr": []
            },
            "returning": False,
            "sql": "SELECT id, name FROM conf_users ORDER BY id ASC",
            "write": False
          },
          "wirePassthrough": True
        },
        {
          "component": "pluck",
          "id": "n1",
          "outType": {
            "arr": "value"
          },
          "parent": "n0",
          "portSchemas": {
            "col": {
              "elemType": "string",
              "required": True,
              "type": "array"
            },
            "rows": {
              "elemType": "value",
              "required": True,
              "type": "array"
            }
          },
          "ports": {
            "col": {
              "arr": [
                "id"
              ]
            },
            "rows": {
              "ref": [
                "n0"
              ]
            }
          },
          "wirePassthrough": True
        },
        {
          "component": "executeSQL",
          "id": "n2",
          "outType": {
            "arr": "value"
          },
          "parent": "n1",
          "portSchemas": {
            "bigint": {
              "required": True,
              "type": "bool"
            },
            "params": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "returning": {
              "required": True,
              "type": "bool"
            },
            "sql": {
              "required": True,
              "type": "string"
            },
            "write": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "bigint": False,
            "params": {
              "arr": [
                {
                  "ref": [
                    "n1"
                  ]
                }
              ]
            },
            "returning": False,
            "sql": "SELECT id, author_id, title, status, created_at FROM conf_posts WHERE conf_posts.author_id = ANY(?::@@PG_ARRAY_CAST@@) ORDER BY id ASC",
            "write": False
          },
          "wirePassthrough": True
        },
        {
          "component": "pluck",
          "id": "n3",
          "outType": {
            "arr": "value"
          },
          "parent": "n2",
          "portSchemas": {
            "col": {
              "elemType": "string",
              "required": True,
              "type": "array"
            },
            "rows": {
              "elemType": "value",
              "required": True,
              "type": "array"
            }
          },
          "ports": {
            "col": {
              "arr": [
                "id"
              ]
            },
            "rows": {
              "ref": [
                "n2"
              ]
            }
          },
          "wirePassthrough": True
        },
        {
          "component": "executeSQL",
          "id": "n4",
          "outType": {
            "arr": "value"
          },
          "parent": "n3",
          "portSchemas": {
            "bigint": {
              "required": True,
              "type": "bool"
            },
            "params": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "returning": {
              "required": True,
              "type": "bool"
            },
            "sql": {
              "required": True,
              "type": "string"
            },
            "write": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "bigint": False,
            "params": {
              "arr": [
                {
                  "ref": [
                    "n3"
                  ]
                }
              ]
            },
            "returning": False,
            "sql": "SELECT id, post_id, label FROM conf_tags WHERE conf_tags.post_id = ANY(?::@@PG_ARRAY_CAST@@) ORDER BY id ASC",
            "write": False
          },
          "wirePassthrough": True
        },
        {
          "component": "group",
          "id": "n5",
          "outType": {
            "arr": "value"
          },
          "parent": "n2",
          "portSchemas": {
            "children": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "fk": {
              "elemType": "string",
              "required": True,
              "type": "array"
            },
            "into": {
              "required": True,
              "type": "string"
            },
            "parents": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "pk": {
              "elemType": "string",
              "required": True,
              "type": "array"
            },
            "single": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "children": {
              "ref": [
                "n4"
              ]
            },
            "fk": {
              "arr": [
                "post_id"
              ]
            },
            "into": "tags",
            "parents": {
              "ref": [
                "n2"
              ]
            },
            "pk": {
              "arr": [
                "id"
              ]
            },
            "single": False
          },
          "wirePassthrough": True
        },
        {
          "component": "group",
          "id": "n6",
          "outType": {
            "arr": {
              "name": "UsersWithPostsRow",
              "obj": {
                "id": {
                  "opt": "float"
                },
                "name": {
                  "opt": "string"
                },
                "posts": {
                  "arr": {
                    "name": "UsersWithPostsRow_posts",
                    "obj": {
                      "author_id": {
                        "opt": "float"
                      },
                      "created_at": {
                        "opt": "string"
                      },
                      "id": {
                        "opt": "float"
                      },
                      "status": {
                        "opt": "string"
                      },
                      "tags": {
                        "arr": {
                          "name": "UsersWithPostsRow_posts_tags",
                          "obj": {
                            "id": {
                              "opt": "float"
                            },
                            "label": {
                              "opt": "string"
                            },
                            "post_id": {
                              "opt": "float"
                            }
                          }
                        }
                      },
                      "title": {
                        "opt": "string"
                      }
                    }
                  }
                }
              }
            }
          },
          "parent": "n0",
          "portSchemas": {
            "children": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "fk": {
              "elemType": "string",
              "required": True,
              "type": "array"
            },
            "into": {
              "required": True,
              "type": "string"
            },
            "parents": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "pk": {
              "elemType": "string",
              "required": True,
              "type": "array"
            },
            "single": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "children": {
              "ref": [
                "n5"
              ]
            },
            "fk": {
              "arr": [
                "author_id"
              ]
            },
            "into": "posts",
            "parents": {
              "ref": [
                "n0"
              ]
            },
            "pk": {
              "arr": [
                "id"
              ]
            },
            "single": False
          }
        }
      ],
      "inputPorts": {},
      "name": "usersWithPosts",
      "output": {
        "ref": [
          "n6"
        ]
      },
      "plan": {
        "concurrency": 16,
        "groups": [
          [
            0
          ],
          [
            1
          ],
          [
            2
          ],
          [
            3
          ],
          [
            4
          ],
          [
            5
          ],
          [
            6
          ]
        ]
      },
      "outputType": {
        "arr": {
          "obj": {
            "id": {
              "opt": "float"
            },
            "name": {
              "opt": "string"
            },
            "posts": {
              "arr": {
                "obj": {
                  "author_id": {
                    "opt": "float"
                  },
                  "created_at": {
                    "opt": "string"
                  },
                  "id": {
                    "opt": "float"
                  },
                  "status": {
                    "opt": "string"
                  },
                  "tags": {
                    "arr": {
                      "obj": {
                        "id": {
                          "opt": "float"
                        },
                        "label": {
                          "opt": "string"
                        },
                        "post_id": {
                          "opt": "float"
                        }
                      },
                      "name": "UsersWithPostsRow_posts_tags"
                    }
                  },
                  "title": {
                    "opt": "string"
                  }
                },
                "name": "UsersWithPostsRow_posts"
              }
            }
          },
          "name": "UsersWithPostsRow"
        }
      }
    },
    {
      "body": [
        {
          "component": "executeSQL",
          "id": "n0",
          "outType": {
            "arr": "value"
          },
          "portSchemas": {
            "bigint": {
              "required": True,
              "type": "bool"
            },
            "params": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "returning": {
              "required": True,
              "type": "bool"
            },
            "sql": {
              "required": True,
              "type": "string"
            },
            "write": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "bigint": False,
            "params": {
              "arr": []
            },
            "returning": False,
            "sql": "SELECT id, author_id, title, status, created_at FROM conf_posts ORDER BY id ASC",
            "write": False
          },
          "wirePassthrough": True
        },
        {
          "component": "pluck",
          "id": "n1",
          "outType": {
            "arr": "value"
          },
          "parent": "n0",
          "portSchemas": {
            "col": {
              "elemType": "string",
              "required": True,
              "type": "array"
            },
            "rows": {
              "elemType": "value",
              "required": True,
              "type": "array"
            }
          },
          "ports": {
            "col": {
              "arr": [
                "author_id"
              ]
            },
            "rows": {
              "ref": [
                "n0"
              ]
            }
          },
          "wirePassthrough": True
        },
        {
          "component": "executeSQL",
          "id": "n2",
          "outType": {
            "arr": "value"
          },
          "parent": "n1",
          "portSchemas": {
            "bigint": {
              "required": True,
              "type": "bool"
            },
            "params": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "returning": {
              "required": True,
              "type": "bool"
            },
            "sql": {
              "required": True,
              "type": "string"
            },
            "write": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "bigint": False,
            "params": {
              "arr": [
                {
                  "ref": [
                    "n1"
                  ]
                }
              ]
            },
            "returning": False,
            "sql": "SELECT id, name, post_count FROM conf_users WHERE conf_users.id = ANY(?::@@PG_ARRAY_CAST@@)",
            "write": False
          },
          "wirePassthrough": True
        },
        {
          "component": "group",
          "id": "n3",
          "outType": {
            "arr": {
              "name": "PostsWithAuthorRow",
              "obj": {
                "author": {
                  "opt": {
                    "name": "PostsWithAuthorRow_author",
                    "obj": {
                      "id": {
                        "opt": "float"
                      },
                      "name": {
                        "opt": "string"
                      },
                      "post_count": {
                        "opt": "float"
                      }
                    }
                  }
                },
                "author_id": {
                  "opt": "float"
                },
                "created_at": {
                  "opt": "string"
                },
                "id": {
                  "opt": "float"
                },
                "status": {
                  "opt": "string"
                },
                "title": {
                  "opt": "string"
                }
              }
            }
          },
          "parent": "n0",
          "portSchemas": {
            "children": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "fk": {
              "elemType": "string",
              "required": True,
              "type": "array"
            },
            "into": {
              "required": True,
              "type": "string"
            },
            "parents": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "pk": {
              "elemType": "string",
              "required": True,
              "type": "array"
            },
            "single": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "children": {
              "ref": [
                "n2"
              ]
            },
            "fk": {
              "arr": [
                "id"
              ]
            },
            "into": "author",
            "parents": {
              "ref": [
                "n0"
              ]
            },
            "pk": {
              "arr": [
                "author_id"
              ]
            },
            "single": True
          }
        }
      ],
      "inputPorts": {},
      "name": "postsWithAuthor",
      "output": {
        "ref": [
          "n3"
        ]
      },
      "plan": {
        "concurrency": 16,
        "groups": [
          [
            0
          ],
          [
            1
          ],
          [
            2
          ],
          [
            3
          ]
        ]
      },
      "outputType": {
        "arr": {
          "obj": {
            "author": {
              "opt": {
                "obj": {
                  "id": {
                    "opt": "float"
                  },
                  "name": {
                    "opt": "string"
                  },
                  "post_count": {
                    "opt": "float"
                  }
                },
                "name": "PostsWithAuthorRow_author"
              }
            },
            "author_id": {
              "opt": "float"
            },
            "created_at": {
              "opt": "string"
            },
            "id": {
              "opt": "float"
            },
            "status": {
              "opt": "string"
            },
            "title": {
              "opt": "string"
            }
          },
          "name": "PostsWithAuthorRow"
        }
      }
    },
    {
      "body": [
        {
          "component": "executeSQL",
          "id": "n0",
          "outType": {
            "arr": "value"
          },
          "portSchemas": {
            "bigint": {
              "required": True,
              "type": "bool"
            },
            "params": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "returning": {
              "required": True,
              "type": "bool"
            },
            "sql": {
              "required": True,
              "type": "string"
            },
            "write": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "bigint": False,
            "params": {
              "arr": []
            },
            "returning": False,
            "sql": "SELECT id, name FROM conf_users ORDER BY id ASC",
            "write": False
          },
          "wirePassthrough": True
        },
        {
          "component": "pluck",
          "id": "n1",
          "outType": {
            "arr": "value"
          },
          "parent": "n0",
          "portSchemas": {
            "col": {
              "elemType": "string",
              "required": True,
              "type": "array"
            },
            "rows": {
              "elemType": "value",
              "required": True,
              "type": "array"
            }
          },
          "ports": {
            "col": {
              "arr": [
                "id"
              ]
            },
            "rows": {
              "ref": [
                "n0"
              ]
            }
          },
          "wirePassthrough": True
        },
        {
          "component": "executeSQL",
          "id": "n2",
          "outType": {
            "arr": "value"
          },
          "parent": "n1",
          "portSchemas": {
            "bigint": {
              "required": True,
              "type": "bool"
            },
            "guard": {
              "required": False,
              "type": "value"
            },
            "params": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "returning": {
              "required": True,
              "type": "bool"
            },
            "sql": {
              "required": True,
              "type": "string"
            },
            "whereDynamic": {
              "required": False,
              "type": "value"
            },
            "write": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "bigint": False,
            "guard": {
              "obj": {
                "limit": 2,
                "model": "conf_posts",
                "relation": "cappedPosts"
              }
            },
            "params": {
              "arr": [
                {
                  "ref": [
                    "n1"
                  ]
                }
              ]
            },
            "returning": False,
            "sql": "SELECT id, author_id, title, status, created_at FROM conf_posts WHERE conf_posts.author_id = ANY(?::@@PG_ARRAY_CAST@@) ORDER BY id ASC",
            "whereDynamic": None,
            "write": False
          },
          "wirePassthrough": True
        },
        {
          "component": "group",
          "id": "n3",
          "outType": {
            "arr": {
              "name": "UsersWithCappedPostsRow",
              "obj": {
                "cappedPosts": {
                  "arr": {
                    "name": "UsersWithCappedPostsRow_cappedPosts",
                    "obj": {
                      "author_id": {
                        "opt": "float"
                      },
                      "created_at": {
                        "opt": "string"
                      },
                      "id": {
                        "opt": "float"
                      },
                      "status": {
                        "opt": "string"
                      },
                      "title": {
                        "opt": "string"
                      }
                    }
                  }
                },
                "id": {
                  "opt": "float"
                },
                "name": {
                  "opt": "string"
                }
              }
            }
          },
          "parent": "n0",
          "portSchemas": {
            "children": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "fk": {
              "elemType": "string",
              "required": True,
              "type": "array"
            },
            "into": {
              "required": True,
              "type": "string"
            },
            "parents": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "pk": {
              "elemType": "string",
              "required": True,
              "type": "array"
            },
            "single": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "children": {
              "ref": [
                "n2"
              ]
            },
            "fk": {
              "arr": [
                "author_id"
              ]
            },
            "into": "cappedPosts",
            "parents": {
              "ref": [
                "n0"
              ]
            },
            "pk": {
              "arr": [
                "id"
              ]
            },
            "single": False
          }
        }
      ],
      "inputPorts": {},
      "name": "usersWithCappedPosts",
      "output": {
        "ref": [
          "n3"
        ]
      },
      "plan": {
        "concurrency": 16,
        "groups": [
          [
            0
          ],
          [
            1
          ],
          [
            2
          ],
          [
            3
          ]
        ]
      },
      "outputType": {
        "arr": {
          "obj": {
            "cappedPosts": {
              "arr": {
                "obj": {
                  "author_id": {
                    "opt": "float"
                  },
                  "created_at": {
                    "opt": "string"
                  },
                  "id": {
                    "opt": "float"
                  },
                  "status": {
                    "opt": "string"
                  },
                  "title": {
                    "opt": "string"
                  }
                },
                "name": "UsersWithCappedPostsRow_cappedPosts"
              }
            },
            "id": {
              "opt": "float"
            },
            "name": {
              "opt": "string"
            }
          },
          "name": "UsersWithCappedPostsRow"
        }
      }
    },
    {
      "body": [
        {
          "component": "executeSQL",
          "id": "n0",
          "outType": {
            "arr": "value"
          },
          "portSchemas": {
            "bigint": {
              "required": True,
              "type": "bool"
            },
            "params": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "returning": {
              "required": True,
              "type": "bool"
            },
            "sql": {
              "required": True,
              "type": "string"
            },
            "write": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "bigint": False,
            "params": {
              "arr": []
            },
            "returning": False,
            "sql": "SELECT id, name FROM conf_users ORDER BY id ASC",
            "write": False
          },
          "wirePassthrough": True
        },
        {
          "component": "pluck",
          "id": "n1",
          "outType": {
            "arr": "value"
          },
          "parent": "n0",
          "portSchemas": {
            "col": {
              "elemType": "string",
              "required": True,
              "type": "array"
            },
            "rows": {
              "elemType": "value",
              "required": True,
              "type": "array"
            }
          },
          "ports": {
            "col": {
              "arr": [
                "id"
              ]
            },
            "rows": {
              "ref": [
                "n0"
              ]
            }
          },
          "wirePassthrough": True
        },
        {
          "component": "executeSQL",
          "id": "n2",
          "outType": {
            "arr": "value"
          },
          "parent": "n1",
          "portSchemas": {
            "bigint": {
              "required": True,
              "type": "bool"
            },
            "params": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "returning": {
              "required": True,
              "type": "bool"
            },
            "sql": {
              "required": True,
              "type": "string"
            },
            "write": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "bigint": False,
            "params": {
              "arr": [
                {
                  "ref": [
                    "n1"
                  ]
                }
              ]
            },
            "returning": False,
            "sql": "SELECT id, author_id, title, status, created_at FROM conf_posts WHERE conf_posts.author_id = ANY(?::@@PG_ARRAY_CAST@@) ORDER BY id ASC",
            "write": False
          },
          "wirePassthrough": True
        },
        {
          "component": "group",
          "id": "n3",
          "outType": {
            "arr": {
              "name": "UsersWithUncappedPostsRow",
              "obj": {
                "id": {
                  "opt": "float"
                },
                "name": {
                  "opt": "string"
                },
                "uncappedPosts": {
                  "arr": {
                    "name": "UsersWithUncappedPostsRow_uncappedPosts",
                    "obj": {
                      "author_id": {
                        "opt": "float"
                      },
                      "created_at": {
                        "opt": "string"
                      },
                      "id": {
                        "opt": "float"
                      },
                      "status": {
                        "opt": "string"
                      },
                      "title": {
                        "opt": "string"
                      }
                    }
                  }
                }
              }
            }
          },
          "parent": "n0",
          "portSchemas": {
            "children": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "fk": {
              "elemType": "string",
              "required": True,
              "type": "array"
            },
            "into": {
              "required": True,
              "type": "string"
            },
            "parents": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "pk": {
              "elemType": "string",
              "required": True,
              "type": "array"
            },
            "single": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "children": {
              "ref": [
                "n2"
              ]
            },
            "fk": {
              "arr": [
                "author_id"
              ]
            },
            "into": "uncappedPosts",
            "parents": {
              "ref": [
                "n0"
              ]
            },
            "pk": {
              "arr": [
                "id"
              ]
            },
            "single": False
          }
        }
      ],
      "inputPorts": {},
      "name": "usersWithUncappedPosts",
      "output": {
        "ref": [
          "n3"
        ]
      },
      "plan": {
        "concurrency": 16,
        "groups": [
          [
            0
          ],
          [
            1
          ],
          [
            2
          ],
          [
            3
          ]
        ]
      },
      "outputType": {
        "arr": {
          "obj": {
            "id": {
              "opt": "float"
            },
            "name": {
              "opt": "string"
            },
            "uncappedPosts": {
              "arr": {
                "obj": {
                  "author_id": {
                    "opt": "float"
                  },
                  "created_at": {
                    "opt": "string"
                  },
                  "id": {
                    "opt": "float"
                  },
                  "status": {
                    "opt": "string"
                  },
                  "title": {
                    "opt": "string"
                  }
                },
                "name": "UsersWithUncappedPostsRow_uncappedPosts"
              }
            }
          },
          "name": "UsersWithUncappedPostsRow"
        }
      }
    },
    {
      "body": [
        {
          "component": "executeSQL",
          "id": "n0",
          "outType": {
            "arr": "value"
          },
          "portSchemas": {
            "bigint": {
              "required": True,
              "type": "bool"
            },
            "params": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "returning": {
              "required": True,
              "type": "bool"
            },
            "sql": {
              "required": True,
              "type": "string"
            },
            "write": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "bigint": False,
            "params": {
              "arr": []
            },
            "returning": False,
            "sql": "SELECT id, name FROM conf_users ORDER BY id ASC",
            "write": False
          },
          "wirePassthrough": True
        },
        {
          "component": "pluck",
          "id": "n1",
          "outType": {
            "arr": "value"
          },
          "parent": "n0",
          "portSchemas": {
            "col": {
              "elemType": "string",
              "required": True,
              "type": "array"
            },
            "rows": {
              "elemType": "value",
              "required": True,
              "type": "array"
            }
          },
          "ports": {
            "col": {
              "arr": [
                "id"
              ]
            },
            "rows": {
              "ref": [
                "n0"
              ]
            }
          },
          "wirePassthrough": True
        },
        {
          "component": "executeSQL",
          "id": "n2",
          "outType": {
            "arr": "value"
          },
          "parent": "n1",
          "portSchemas": {
            "bigint": {
              "required": True,
              "type": "bool"
            },
            "params": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "returning": {
              "required": True,
              "type": "bool"
            },
            "sql": {
              "required": True,
              "type": "string"
            },
            "write": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "bigint": False,
            "params": {
              "arr": [
                {
                  "ref": [
                    "n1"
                  ]
                }
              ]
            },
            "returning": False,
            "sql": "SELECT conf_posts.* FROM unnest(?::@@PG_ARRAY_CAST@@) AS _keys(key) CROSS JOIN LATERAL (SELECT * FROM conf_posts WHERE conf_posts.author_id = _keys.key ORDER BY id ASC LIMIT 1) conf_posts",
            "write": False
          },
          "wirePassthrough": True
        },
        {
          "component": "group",
          "id": "n3",
          "outType": {
            "arr": {
              "name": "UsersWithTopPostsRow",
              "obj": {
                "id": {
                  "opt": "float"
                },
                "name": {
                  "opt": "string"
                },
                "topPosts": {
                  "arr": {
                    "name": "UsersWithTopPostsRow_topPosts",
                    "obj": {
                      "author_id": {
                        "opt": "float"
                      },
                      "created_at": {
                        "opt": "string"
                      },
                      "id": {
                        "opt": "float"
                      },
                      "status": {
                        "opt": "string"
                      },
                      "title": {
                        "opt": "string"
                      }
                    }
                  }
                }
              }
            }
          },
          "parent": "n0",
          "portSchemas": {
            "children": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "fk": {
              "elemType": "string",
              "required": True,
              "type": "array"
            },
            "into": {
              "required": True,
              "type": "string"
            },
            "parents": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "pk": {
              "elemType": "string",
              "required": True,
              "type": "array"
            },
            "single": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "children": {
              "ref": [
                "n2"
              ]
            },
            "fk": {
              "arr": [
                "author_id"
              ]
            },
            "into": "topPosts",
            "parents": {
              "ref": [
                "n0"
              ]
            },
            "pk": {
              "arr": [
                "id"
              ]
            },
            "single": False
          }
        }
      ],
      "inputPorts": {},
      "name": "usersWithTopPosts",
      "output": {
        "ref": [
          "n3"
        ]
      },
      "plan": {
        "concurrency": 16,
        "groups": [
          [
            0
          ],
          [
            1
          ],
          [
            2
          ],
          [
            3
          ]
        ]
      },
      "outputType": {
        "arr": {
          "obj": {
            "id": {
              "opt": "float"
            },
            "name": {
              "opt": "string"
            },
            "topPosts": {
              "arr": {
                "obj": {
                  "author_id": {
                    "opt": "float"
                  },
                  "created_at": {
                    "opt": "string"
                  },
                  "id": {
                    "opt": "float"
                  },
                  "status": {
                    "opt": "string"
                  },
                  "title": {
                    "opt": "string"
                  }
                },
                "name": "UsersWithTopPostsRow_topPosts"
              }
            }
          },
          "name": "UsersWithTopPostsRow"
        }
      }
    },
    {
      "body": [
        {
          "component": "executeSQL",
          "id": "n0",
          "outType": {
            "arr": {
              "name": "WriteSummary",
              "obj": {
                "changes": "int",
                "lastInsertRowid": "int"
              }
            }
          },
          "portSchemas": {
            "bigint": {
              "required": True,
              "type": "bool"
            },
            "params": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "returning": {
              "required": True,
              "type": "bool"
            },
            "sql": {
              "required": True,
              "type": "string"
            },
            "write": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "bigint": False,
            "params": {
              "arr": [
                {
                  "ref": [
                    "authorId"
                  ]
                },
                {
                  "ref": [
                    "createdAt"
                  ]
                },
                {
                  "ref": [
                    "id"
                  ]
                },
                {
                  "ref": [
                    "status"
                  ]
                },
                {
                  "ref": [
                    "title"
                  ]
                }
              ]
            },
            "returning": False,
            "sql": "INSERT INTO conf_posts (author_id, created_at, id, status, title) VALUES (?, ?, ?, ?, ?)",
            "write": True
          }
        }
      ],
      "inputPorts": {
        "authorId": {
          "required": True,
          "type": "int"
        },
        "createdAt": {
          "required": True,
          "type": "string"
        },
        "id": {
          "required": True,
          "type": "int"
        },
        "status": {
          "required": True,
          "type": "string"
        },
        "title": {
          "required": True,
          "type": "string"
        }
      },
      "name": "createPost",
      "output": {
        "ref": [
          "n0"
        ]
      },
      "plan": {
        "concurrency": 16,
        "groups": [
          [
            0
          ]
        ]
      },
      "outputType": {
        "arr": {
          "obj": {
            "changes": "int",
            "lastInsertRowid": "int"
          },
          "name": "WriteSummary"
        }
      }
    },
    {
      "body": [
        {
          "component": "executeSQL",
          "id": "n0",
          "outType": {
            "arr": {
              "name": "WriteSummary",
              "obj": {
                "changes": "int",
                "lastInsertRowid": "int"
              }
            }
          },
          "portSchemas": {
            "bigint": {
              "required": True,
              "type": "bool"
            },
            "params": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "returning": {
              "required": True,
              "type": "bool"
            },
            "sql": {
              "required": True,
              "type": "string"
            },
            "write": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "bigint": False,
            "params": {
              "arr": [
                {
                  "ref": [
                    "title"
                  ]
                },
                {
                  "ref": [
                    "id"
                  ]
                }
              ]
            },
            "returning": False,
            "sql": "UPDATE conf_posts SET title = ? WHERE id = ?",
            "write": True
          }
        }
      ],
      "inputPorts": {
        "id": {
          "required": True,
          "type": "int"
        },
        "title": {
          "required": True,
          "type": "string"
        }
      },
      "name": "renamePost",
      "output": {
        "ref": [
          "n0"
        ]
      },
      "plan": {
        "concurrency": 16,
        "groups": [
          [
            0
          ]
        ]
      },
      "outputType": {
        "arr": {
          "obj": {
            "changes": "int",
            "lastInsertRowid": "int"
          },
          "name": "WriteSummary"
        }
      }
    },
    {
      "body": [
        {
          "component": "executeSQL",
          "id": "n0",
          "outType": {
            "arr": {
              "name": "WriteSummary",
              "obj": {
                "changes": "int",
                "lastInsertRowid": "int"
              }
            }
          },
          "portSchemas": {
            "bigint": {
              "required": True,
              "type": "bool"
            },
            "params": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "returning": {
              "required": True,
              "type": "bool"
            },
            "sql": {
              "required": True,
              "type": "string"
            },
            "write": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "bigint": False,
            "params": {
              "arr": [
                {
                  "ref": [
                    "id"
                  ]
                }
              ]
            },
            "returning": False,
            "sql": "DELETE FROM conf_posts WHERE id = ?",
            "write": True
          }
        }
      ],
      "inputPorts": {
        "id": {
          "required": True,
          "type": "int"
        }
      },
      "name": "removePost",
      "output": {
        "ref": [
          "n0"
        ]
      },
      "plan": {
        "concurrency": 16,
        "groups": [
          [
            0
          ]
        ]
      },
      "outputType": {
        "arr": {
          "obj": {
            "changes": "int",
            "lastInsertRowid": "int"
          },
          "name": "WriteSummary"
        }
      }
    },
    {
      "body": [
        {
          "component": "executeSQL",
          "id": "n0",
          "outType": {
            "arr": {
              "name": "CreatePostReturningRow",
              "obj": {
                "id": {
                  "opt": "float"
                },
                "title": {
                  "opt": "string"
                }
              }
            }
          },
          "portSchemas": {
            "bigint": {
              "required": True,
              "type": "bool"
            },
            "params": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "returning": {
              "required": True,
              "type": "bool"
            },
            "sql": {
              "required": True,
              "type": "string"
            },
            "write": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "bigint": False,
            "params": {
              "arr": [
                {
                  "ref": [
                    "authorId"
                  ]
                },
                {
                  "ref": [
                    "createdAt"
                  ]
                },
                {
                  "ref": [
                    "id"
                  ]
                },
                {
                  "ref": [
                    "status"
                  ]
                },
                {
                  "ref": [
                    "title"
                  ]
                }
              ]
            },
            "returning": True,
            "sql": "INSERT INTO conf_posts (author_id, created_at, id, status, title) VALUES (?, ?, ?, ?, ?) RETURNING id, title",
            "write": True
          }
        }
      ],
      "inputPorts": {
        "authorId": {
          "required": True,
          "type": "int"
        },
        "createdAt": {
          "required": True,
          "type": "string"
        },
        "id": {
          "required": True,
          "type": "int"
        },
        "status": {
          "required": True,
          "type": "string"
        },
        "title": {
          "required": True,
          "type": "string"
        }
      },
      "name": "createPostReturning",
      "output": {
        "ref": [
          "n0"
        ]
      },
      "plan": {
        "concurrency": 16,
        "groups": [
          [
            0
          ]
        ]
      },
      "outputType": {
        "arr": {
          "obj": {
            "id": {
              "opt": "float"
            },
            "title": {
              "opt": "string"
            }
          },
          "name": "CreatePostReturningRow"
        }
      }
    },
    {
      "body": [
        {
          "component": "executeSQL",
          "id": "n0",
          "outType": {
            "arr": {
              "name": "RenamePostReturningRow",
              "obj": {
                "id": {
                  "opt": "float"
                },
                "title": {
                  "opt": "string"
                }
              }
            }
          },
          "portSchemas": {
            "bigint": {
              "required": True,
              "type": "bool"
            },
            "params": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "returning": {
              "required": True,
              "type": "bool"
            },
            "sql": {
              "required": True,
              "type": "string"
            },
            "write": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "bigint": False,
            "params": {
              "arr": [
                {
                  "ref": [
                    "title"
                  ]
                },
                {
                  "ref": [
                    "id"
                  ]
                }
              ]
            },
            "returning": True,
            "sql": "UPDATE conf_posts SET title = ? WHERE id = ? RETURNING id, title",
            "write": True
          }
        }
      ],
      "inputPorts": {
        "id": {
          "required": True,
          "type": "int"
        },
        "title": {
          "required": True,
          "type": "string"
        }
      },
      "name": "renamePostReturning",
      "output": {
        "ref": [
          "n0"
        ]
      },
      "plan": {
        "concurrency": 16,
        "groups": [
          [
            0
          ]
        ]
      },
      "outputType": {
        "arr": {
          "obj": {
            "id": {
              "opt": "float"
            },
            "title": {
              "opt": "string"
            }
          },
          "name": "RenamePostReturningRow"
        }
      }
    },
    {
      "body": [
        {
          "component": "executeSQL",
          "id": "n0",
          "outType": {
            "arr": {
              "name": "RemovePostReturningRow",
              "obj": {
                "id": {
                  "opt": "float"
                },
                "title": {
                  "opt": "string"
                }
              }
            }
          },
          "portSchemas": {
            "bigint": {
              "required": True,
              "type": "bool"
            },
            "params": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "returning": {
              "required": True,
              "type": "bool"
            },
            "sql": {
              "required": True,
              "type": "string"
            },
            "write": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "bigint": False,
            "params": {
              "arr": [
                {
                  "ref": [
                    "id"
                  ]
                }
              ]
            },
            "returning": True,
            "sql": "DELETE FROM conf_posts WHERE id = ? RETURNING id, title",
            "write": True
          }
        }
      ],
      "inputPorts": {
        "id": {
          "required": True,
          "type": "int"
        }
      },
      "name": "removePostReturning",
      "output": {
        "ref": [
          "n0"
        ]
      },
      "plan": {
        "concurrency": 16,
        "groups": [
          [
            0
          ]
        ]
      },
      "outputType": {
        "arr": {
          "obj": {
            "id": {
              "opt": "float"
            },
            "title": {
              "opt": "string"
            }
          },
          "name": "RemovePostReturningRow"
        }
      }
    },
    {
      "body": [
        {
          "component": "executeSQL",
          "id": "n0",
          "outType": {
            "arr": {
              "name": "TypedRowsRow",
              "obj": {
                "flag": {
                  "opt": "float"
                },
                "id": {
                  "opt": "float"
                },
                "label": {
                  "opt": "string"
                },
                "ts": {
                  "opt": "string"
                }
              }
            }
          },
          "portSchemas": {
            "bigint": {
              "required": True,
              "type": "bool"
            },
            "params": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "returning": {
              "required": True,
              "type": "bool"
            },
            "sql": {
              "required": True,
              "type": "string"
            },
            "write": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "bigint": False,
            "params": {
              "arr": []
            },
            "returning": False,
            "sql": "SELECT id, ts, flag, label FROM conf_typed ORDER BY id ASC",
            "write": False
          }
        }
      ],
      "inputPorts": {},
      "name": "typedRows",
      "output": {
        "ref": [
          "n0"
        ]
      },
      "plan": {
        "concurrency": 16,
        "groups": [
          [
            0
          ]
        ]
      },
      "outputType": {
        "arr": {
          "obj": {
            "flag": {
              "opt": "float"
            },
            "id": {
              "opt": "float"
            },
            "label": {
              "opt": "string"
            },
            "ts": {
              "opt": "string"
            }
          },
          "name": "TypedRowsRow"
        }
      }
    },
    {
      "body": [
        {
          "component": "executeSQL",
          "id": "n0",
          "outType": {
            "arr": {
              "name": "WriteSummary",
              "obj": {
                "changes": "int",
                "lastInsertRowid": "int"
              }
            }
          },
          "portSchemas": {
            "bigint": {
              "required": True,
              "type": "bool"
            },
            "params": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "returning": {
              "required": True,
              "type": "bool"
            },
            "sql": {
              "required": True,
              "type": "string"
            },
            "write": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "bigint": False,
            "params": {
              "arr": [
                {
                  "ref": [
                    "rows_id"
                  ]
                },
                {
                  "ref": [
                    "rows_label"
                  ]
                },
                {
                  "ref": [
                    "rows_post_id"
                  ]
                }
              ]
            },
            "returning": False,
            "sql": "INSERT INTO conf_tags (id, label, post_id) SELECT v.id, v.label, v.post_id FROM UNNEST(?::int[], ?::text[], ?::int[]) AS v(id, label, post_id)",
            "write": True
          }
        }
      ],
      "inputPorts": {
        "rows_id": {
          "elemType": "int",
          "required": True,
          "type": "array"
        },
        "rows_label": {
          "elemType": "string",
          "required": True,
          "type": "array"
        },
        "rows_post_id": {
          "elemType": "int",
          "required": True,
          "type": "array"
        }
      },
      "name": "createTags",
      "output": {
        "ref": [
          "n0"
        ]
      },
      "plan": {
        "concurrency": 16,
        "groups": [
          [
            0
          ]
        ]
      },
      "outputType": {
        "arr": {
          "obj": {
            "changes": "int",
            "lastInsertRowid": "int"
          },
          "name": "WriteSummary"
        }
      }
    },
    {
      "body": [
        {
          "component": "executeSQL",
          "id": "n0",
          "outType": {
            "arr": {
              "name": "WriteSummary",
              "obj": {
                "changes": "int",
                "lastInsertRowid": "int"
              }
            }
          },
          "portSchemas": {
            "bigint": {
              "required": True,
              "type": "bool"
            },
            "params": {
              "elemType": "value",
              "required": True,
              "type": "array"
            },
            "returning": {
              "required": True,
              "type": "bool"
            },
            "sql": {
              "required": True,
              "type": "string"
            },
            "write": {
              "required": True,
              "type": "bool"
            }
          },
          "ports": {
            "bigint": False,
            "params": {
              "arr": [
                {
                  "ref": [
                    "ids"
                  ]
                }
              ]
            },
            "returning": False,
            "sql": "DELETE FROM conf_tags WHERE id = ANY(?)",
            "write": True
          }
        }
      ],
      "inputPorts": {
        "ids": {
          "elemType": "int",
          "required": True,
          "type": "array"
        }
      },
      "name": "removeTags",
      "output": {
        "ref": [
          "n0"
        ]
      },
      "plan": {
        "concurrency": 16,
        "groups": [
          [
            0
          ]
        ]
      },
      "outputType": {
        "arr": {
          "obj": {
            "changes": "int",
            "lastInsertRowid": "int"
          },
          "name": "WriteSummary"
        }
      }
    }
  ]
}


def _load_generated_module():
    # load-time fail-closed checks (#208 prepared-artifact discipline).
    for _k, _want in EXPECTED_SPEC_VERSIONS.items():
        _got = SPEC_VERSIONS.get(_k)
        if _got != _want:
            raise RuntimeError(
                "behavior-contracts generated module: spec-version skew for '%s' "
                "(generated=%s, runtime=%s) — regenerate against this runtime (fail-closed)"
                % (_k, _want, _got)
            )
    # fingerprint-gated adopt: recompute the canonical fingerprint, verify it against the baked
    # constant, and mint the in-process provenance handle. A modified/corrupted literal is loud-rejected.
    try:
        return load_compiled_ir(IR_DOC, IR_FINGERPRINT)
    except ProvenanceError as _e:
        raise RuntimeError(
            "behavior-contracts generated module: IR fingerprint mismatch (baked=%s) — "
            "the generated code was modified or corrupted (fail-closed)" % IR_FINGERPRINT
        ) from _e


IR = _load_generated_module()


def bind(handlers):
    """Inject handlers (boundary injection; catalog name -> implementation) and get
    one callable per component. Each call delegates to the runtime core's
    run_behavior over the embedded IR (dynamic-path equivalent — §7.3)."""

    def _make(name):
        def _call(input=None):
            return run_behavior(IR, handlers, dict(input or {}), name)

        return _call

    return {name: _make(name) for name in COMPONENT_NAMES}


class Conformance:
    """#192: namespaced 1:1 positional entries (thin wrappers over run_behavior)."""

    @staticmethod
    def posts(authorId, handlers):
        return run_behavior(IR, handlers, {"authorId": authorId}, "posts")

    @staticmethod
    def posts_top(handlers):
        return run_behavior(IR, handlers, {}, "postsTop")

    @staticmethod
    def page(limit, offset, handlers):
        return run_behavior(IR, handlers, {"limit": limit, "offset": offset}, "page")

    @staticmethod
    def posts_by_ids(ids, handlers):
        return run_behavior(IR, handlers, {"ids": ids}, "postsByIds")

    @staticmethod
    def feed(authorId, status, since, handlers):
        return run_behavior(IR, handlers, {"authorId": authorId, "status": status, "since": since}, "feed")

    @staticmethod
    def users_with_posts(handlers):
        return run_behavior(IR, handlers, {}, "usersWithPosts")

    @staticmethod
    def posts_with_author(handlers):
        return run_behavior(IR, handlers, {}, "postsWithAuthor")

    @staticmethod
    def users_with_capped_posts(handlers):
        return run_behavior(IR, handlers, {}, "usersWithCappedPosts")

    @staticmethod
    def users_with_uncapped_posts(handlers):
        return run_behavior(IR, handlers, {}, "usersWithUncappedPosts")

    @staticmethod
    def users_with_top_posts(handlers):
        return run_behavior(IR, handlers, {}, "usersWithTopPosts")

    @staticmethod
    def create_post(id, authorId, title, status, createdAt, handlers):
        return run_behavior(IR, handlers, {"id": id, "authorId": authorId, "title": title, "status": status, "createdAt": createdAt}, "createPost")

    @staticmethod
    def rename_post(title, id, handlers):
        return run_behavior(IR, handlers, {"title": title, "id": id}, "renamePost")

    @staticmethod
    def remove_post(id, handlers):
        return run_behavior(IR, handlers, {"id": id}, "removePost")

    @staticmethod
    def create_post_returning(id, authorId, title, status, createdAt, handlers):
        return run_behavior(IR, handlers, {"id": id, "authorId": authorId, "title": title, "status": status, "createdAt": createdAt}, "createPostReturning")

    @staticmethod
    def rename_post_returning(title, id, handlers):
        return run_behavior(IR, handlers, {"title": title, "id": id}, "renamePostReturning")

    @staticmethod
    def remove_post_returning(id, handlers):
        return run_behavior(IR, handlers, {"id": id}, "removePostReturning")

    @staticmethod
    def typed_rows(handlers):
        return run_behavior(IR, handlers, {}, "typedRows")

    @staticmethod
    def create_tags(rows_id, rows_post_id, rows_label, handlers):
        return run_behavior(IR, handlers, {"rows_id": rows_id, "rows_post_id": rows_post_id, "rows_label": rows_label}, "createTags")

    @staticmethod
    def remove_tags(ids, handlers):
        return run_behavior(IR, handlers, {"ids": ids}, "removeTags")
