#!/usr/bin/env node
/**
 * Every HAND-WRITTEN go file is gofmt-clean (#204).
 *
 * `cargo fmt --all -- --check` has gated rust since #168. Go had `go build` / `go vet` / `go test` and
 * nothing else, and gofmt affects none of them — so four hand-written files sat unformatted with no
 * symptom of any kind: `conformance/livedb/livedb_runner.go` and the three
 * `lm_bench/lm_orm_native/target_<dialect>.go`.
 *
 * The bc-GENERATED modules are EXEMPT, and that is a measured decision, not a convenience. bc's go
 * emitter output is not gofmt-clean (its `const` blocks and one-line `func` bodies align on a
 * different column), and the generated files are byte-compared against a fresh generation. Running
 * `gofmt -w` on one is therefore a DRIFT:
 *
 *     gofmt -w go/litedbmodel_runtime/wire/wire.go
 *     bash benchmark/crosslang/gen-native.sh check
 *       → bc: DRIFT — …/go/litedbmodel_runtime/wire/wire.go differs from a fresh generation
 *         exit 1
 *
 * Rust has the same problem and bc solves it there by emitting `#[rustfmt::skip]` on the items whose
 * layout depends on the IR (rust/livedb_runner/src/gen/postgres.rs:102 and on). gofmt has no such
 * directive — no pragma, no config, no per-file opt-out — so for go the only two options are "format
 * the output and fight the drift gate forever" or "exempt it here". Exempting it is not a hole: those
 * files are gated on something STRICTER than formatting, namely byte-equality with bc's output
 * (`bash benchmark/crosslang/gen-native.sh check` for the bench modules + the shared wire package,
 * `npm run conformance:check:livedb` for the conformance modules).
 *
 * So the exemption is not a path list this script trusts. It is checked BOTH WAYS: the files whose
 * header says bc generated them must be EXACTLY {@link GENERATED}. A hand-written file cannot drift
 * into the exempt set without the marker (the derived set would not grow, and the list would name a
 * file the scan does not find → red), and a newly generated file cannot appear unlisted (the derived
 * set grows past the list → red) — which matters because a new dialect or a new endpoint adds
 * generated modules, and the natural mistake is to leave one out of a hand-kept list.
 *
 * It is red when any of the following holds:
 *
 *   - `gofmt` could not be run at all, or exited for a reason other than reporting unformatted files.
 *   - a HAND-WRITTEN go file is not gofmt-clean — each one NAMED.
 *   - the bc-marked files are not exactly {@link GENERATED}, in either direction.
 *   - the scan found no go files, or no generated files: either means the scan is wrong, and every
 *     check here is only as strong as the scan.
 *
 * What it does NOT check, and both fall GREEN: whether an exempt file really is bc's current output
 * (that is the `bc check` drift gate named above, and it is the reason the exemption is safe); and
 * gofmt is not `go vet` — formatting says nothing about correctness.
 *
 *   node scripts/check-go-fmt.mjs
 */
import { execFileSync } from 'node:child_process';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const GO_DIR = join(ROOT, 'go');

/**
 * The go modules bc GENERATES, relative to `go/` — the emitter's output, byte-gated against a fresh
 * generation, and therefore exempt from gofmt. Kept in step with the tree by the bidirectional check
 * below, so adding a dialect or an endpoint that emits a new module fails here until it is listed.
 *
 * Who writes each one:
 *   litedbmodel_runtime/wire/wire.go               bc `--shared-types-out` (gen-native.sh, sqlite run)
 *   lm_bench/lm_orm_native/gen/bench<dialect>/…    bc `--out`              (gen-native.sh, per dialect)
 *   conformance/gen/<dialect>/…                    bc `--out`              (conformance/gen-livedb.ts)
 */
const GENERATED = [
  'conformance/gen/mysql/behaviors.go',
  'conformance/gen/postgres/behaviors.go',
  'litedbmodel_runtime/wire/wire.go',
  'lm_bench/lm_orm_native/gen/benchmysql/behaviors.go',
  'lm_bench/lm_orm_native/gen/benchpostgres/behaviors.go',
  'lm_bench/lm_orm_native/gen/benchsqlite/behaviors.go',
];

/** bc stamps this on the first line of every module it emits. */
const MARKER = 'GENERATED by behavior-contracts';
/** How far into a file the marker may appear — bc writes it on line 1; a few lines of slack, no more. */
const MARKER_LINES = 3;

/** Every `*.go` under `go/`, relative to `go/`. */
function goFiles(dir) {
  const out = [];
  for (const e of readdirSync(dir)) {
    if (e === 'vendor' || e === 'testdata' || e.startsWith('.')) continue;
    const p = join(dir, e);
    if (statSync(p).isDirectory()) out.push(...goFiles(p));
    else if (e.endsWith('.go')) out.push(relative(GO_DIR, p));
  }
  return out;
}

const all = goFiles(GO_DIR).sort();
const problems = [];
if (all.length === 0) {
  console.error('❌ no .go files found under go/ — the scan is wrong, and every check below would pass vacuously.');
  process.exit(1);
}

// ── the exemption, checked against the files themselves ─────────────────────
const marked = all.filter((f) => readFileSync(join(GO_DIR, f), 'utf8').split('\n', MARKER_LINES).some((l) => l.includes(MARKER)));
if (marked.length === 0) {
  console.error(`❌ no go file under go/ carries bc's "${MARKER}" marker in its first ${MARKER_LINES} lines, so the exemption below rests on nothing. Either the marker changed or the scan is wrong.`);
  process.exit(1);
}
const unlisted = marked.filter((f) => !GENERATED.includes(f)).sort();
const missing = GENERATED.filter((f) => !marked.includes(f)).sort();
if (unlisted.length > 0) {
  problems.push(
    `${unlisted.length} go file(s) say bc GENERATED them but are not in this script's GENERATED list, so they are being gofmt-checked as if hand-written — and if the emitter's output is not gofmt-clean, no one can make them pass:\n` +
      unlisted.map((f) => `      ${f}`).join('\n') +
      `\n\n      If bc emits it, list it (a new dialect / a new endpoint adds modules). If it is\n` +
      `      hand-written, the marker does not belong in it.`,
  );
}
if (missing.length > 0) {
  problems.push(
    `${missing.length} file(s) in GENERATED do not carry bc's marker — either they are gone, or something HAND-WRITTEN is being exempted from gofmt under a generated file's name:\n` +
      missing.map((f) => `      ${f}`).join('\n'),
  );
}

// ── gofmt over the hand-written files ───────────────────────────────────────
// `gofmt -l` names the files whose formatting differs and exits 0 either way; a non-zero exit is
// gofmt failing (a parse error, a missing binary), which is not a formatting verdict and must not be
// read as one.
let listed;
try {
  listed = execFileSync('gofmt', ['-l', '.'], { cwd: GO_DIR, encoding: 'utf8' });
} catch (err) {
  console.error(
    `❌ \`gofmt -l .\` did not run to completion in go/ (${err.message}). That is not a clean formatting verdict, so this will not report one.\n` +
      (err.stderr ? `\n${err.stderr}` : ''),
  );
  process.exit(1);
}
const unformatted = listed.split('\n').map((l) => l.trim()).filter(Boolean).sort();
const handWritten = unformatted.filter((f) => !GENERATED.includes(f));
if (handWritten.length > 0) {
  problems.push(
    `${handWritten.length} hand-written go file(s) are not gofmt-clean. Nothing else will ever say so — gofmt affects neither the build, nor vet, nor the tests:\n` +
      handWritten.map((f) => `      go/${f}`).join('\n') +
      `\n\n      cd go && gofmt -w ${handWritten.join(' ')}`,
  );
}

if (problems.length > 0) {
  console.error('❌ go formatting:\n');
  for (const p of problems) console.error(`  ${p}\n`);
  console.error(`${problems.length} problem(s).`);
  process.exit(1);
}
console.log(
  `✅ all ${all.length - GENERATED.length} hand-written go files under go/ are gofmt-clean (\`gofmt -l\` named ${unformatted.length}, every one of them bc output).\n` +
    `   The ${GENERATED.length} bc-generated modules are EXEMPT because gofmt-ing them is a drift: bc's go output is not\n` +
    `   gofmt-clean and the files are byte-compared against a fresh generation. The exemption is checked BOTH\n` +
    `   ways against the files' own "${MARKER}" marker, so neither an unlisted new\n` +
    `   generated module nor a hand-written file wearing a generated name can slip into it.\n` +
    `   NOT checked, and both fall GREEN: whether an exempt file IS bc's current output — that is\n` +
    `   \`bash benchmark/crosslang/gen-native.sh check\` (bench + wire) and \`npm run conformance:check:livedb\`\n` +
    `   (conformance) — and correctness, which is \`go vet\` and the suite, not a formatter.`,
);
